name: Build dev
on:
  workflow_call: 

jobs:
  triage:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out
        uses: actions/checkout@v2
        
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: node_modules
          
      - name: Extract artifacts
        run: tar -xf node_modules.tar.gz
          
      - name: Build
        run: npm run build
        
      - name: Artifact files
        run: tar -czf deploy.tar.gz dist codedeploy
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: deploy
          path: deploy.tar.gz
