name: Deploy DEV

on:
  push:
    branches:
      - dev

jobs:
  check:
    uses: Nano-IT/workflows/.github/workflows/check.yml@main

  build-dev:
    needs: check
    uses: Nano-IT/workflows/.github/workflows/build.yml@main

  deploy-dev:
    needs: build-dev
    uses: Nano-IT/workflows/.github/workflows/deploy-dev.yml@main
    secrets: inherit
    with:
      tags: "docker.pkg.github.com/tudorteisanu/shoply/dev"
      file:  "codedeploy/Dockerfile"

