name: Install

on:
  workflow_call: 

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i
      - name: Create archive
        run: tar -cvf node_modules.tar node_modules
      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: node_modules
          path: |
             node_modules.tar
