name: Deploy PROD

on:
  push:
    branches:
      - master
      
  workflow_call:
    inputs:
      token:
        required: true
        type: string

jobs:
  check:
    uses: Nano-IT/workflows/.github/workflows/check.yml@main

  release:
    needs: check
    uses: Nano-IT/workflows/.github/workflows/release.yml@main
    with: 
      authToken:  ${{ secrets.DOCKER_AUTH_TOKEN }}

