name: Deploy PROD

on:
  push:
    branches:
      - master

jobs:
  check:
    uses: Nano-IT/workflows/.github/workflows/check.yml@main

  release:
    needs: check
    uses: Nano-IT/workflows/.github/workflows/release.yml@main
    secrets: 
      authToken:  ${{ secrets.DOCKER_AUTH_TOKEN }}

