name: Release

on:
  push:
    branches:
      - master

jobs:
#  check:
#    uses: Nano-IT/workflows/.github/workflows/check.yml@v1

  release:
#    needs: check
    uses: Nano-IT/workflows/.github/workflows/release.yml@v1
    with:
      environment: development
    secrets: inherit
