name: Deploy PROD

on:
  push:
    branches:
      - master

jobs:
#  check:
#    uses: ./.github/workflows/check.yml

  release:
#    needs: check
    uses: ./.github/workflows/release-with-changelog.yml
    secrets: inherit

