name: Release

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - run: git config --global user.name 'Release BOT'
      - run: git config --global user.email 'teisanutudort@gmail.com'
      - run: npm version patch
      - run: echo "::set-env name=HEAD_TAG::$(git tag --points-at HEAD)"
      - run: git tag -a $HEAD_TAG
      - run: git push --tags


