name: Release

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - run: git config --global user.name 'Release BOT'
      - run: git config --global user.email 'teisanutudort@gmail.com'
      - run: npm version patch
      - run: |
          RELEASE=$(grep '"version"' package.json | cut -d '"' -f 4 | head -n 1)
          export RELEASE_VERSION=echo("v${RELEASE})
      - run: git push origin refs/tags/${{ env.RELEASE_VERSION }}


