name: Release

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Update version
        run: npm version patch

      - name: Read package.json
        uses: dutscher/read-package-json-endpoint-actions@v1.33.7
        id: package-json-endpoint

      - uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ steps.package-json-endpoint.outputs.endpoint }}
          message: '${{ steps.package-json-endpoint.outputs.endpoint }}: PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'

#
#
