name: Release

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Update version
        run: npm version patch

      - name: Read package.json
        uses: dutscher/read-package-json-endpoint-actions@v1.33.7
        id: package-json-endpoint

      - name: Push tags
        run: |
          git tag {{ steps.package-json-endpoint.outputs.endpoint }}
          git push --tags
#
#
