name: Release

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - run: git config --global user.name 'Release BOT'
      - run: git config --global user.email 'teisanutudort@gmail.com'
      - run: npm version patch
      - name: Read package.json
        uses: dutscher/read-package-json-endpoint-actions@v1.33.7
        id: package-json-endpoint
      - run: git tag ${{ steps.package-json-endpoint.outputs.endpoint }}
      - run: git push --tags
#
#
