name: Release

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - run: git config --global user.name 'Release BOT'
      - run: git config --global user.email 'teisanutudort@gmail.com'
      - run: npm version patch
      - run: git push --tags
#
#
