name: Release

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - run: git config user.name 'Release BOT'
      - run: git config user.email 'teisanutudort@gmail.com'
      - run: |
          npm version patch
          git push
          git push --tags

