name: Release

on:
  workflow_call:

  workflow_dispatch:
    inputs:
      tag:
        description: 'New tag name'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DOCKER_AUTH_TOKEN }}

      - run: git config user.name 'Release BOT'
      - run: git config user.email 'noreply.release@github.com'

      - run: npm version patch
      - run: git push --tags

