name: Release

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          GITHUB_TOKEN: ${{ secrets.DOCKER_AUTH_TOKEN }}
#
#      - run: git config --global user.name 'Release BOT'
#      - run: git config --global user.email 'teisanutudort@gmail.com'
      - run: npm version patch
      - run: |
          export RELEASE_VERSION=$(grep '"version"' package.json | cut -d '"' -f 4 | head -n 1)
          git tag -a $RELEASE_VERSION -m $RELEASE_VERSION
          git push --tags

