name: Dev deploy steps

on:
  push:
    branches:
      - master

jobs:
  install:
    uses: ./.github/workflows/install.yml
  lint:
    needs: install
    uses: ./.github/workflows/lint.yml
  build-dev:
    needs: lint
    uses: ./.github/workflows/build.yml
  deploy-dev:
    needs: build-dev
    uses: ./.github/workflows/deploy-dev.yml
    secrets:
      USER: ${{ secrets.user }}
      HOST: ${{ secrets.host }}
      DIST: ${{ secrets.dist }}
      KEY: ${{ secrets.key }}
      DOCKER_AUTH_TOKEN: ${{ secrets.DOCKER_AUTH_TOKEN }}
