name: Debug

on:
  push:
    branches:
      - master

jobs:
  call-workflow:
    uses: tudorteisanu/shoply/.github/workflows/debug.yml@master

  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: tudorteisanu/shoply/.github/workflows/debug.yml@master
    with:
      config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
