name: Debug

on:
  push:
    branches: "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./deploy
      
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./debug
