name: Tags

on:
  push:
    tags:
      - '*'

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  deploy-prod:
    needs: lint
    uses: ./.github/workflows/deploy-prod.yml
    secrets: inherit

