name: Tags

on:
  push:
    tags:
      - '*'
  create:
    tags:
      - '*'

jobs:
  check:
    uses: Nano-IT/workflows/.github/workflows/check.yml@main

  build:
    needs: check
    uses: Nano-IT/workflows/.github/workflows/build.yml@main

  deploy:
    needs: build
    uses: Nano-IT/workflows/.github/workflows/deploy-prod.yml@main
    secrets: inherit

