name: Production

on:
  create:
    tags:
      - '*'
    branches-ignore:
      - '*'

jobs:
  return_if_not_master:
    runs-on: ubuntu-latest
    steps:
      - name: Exit if not on production branch
        if: endsWith(github.event.base_ref, 'master') == false
        run: exit -1

  check:
    needs: return_if_not_master
    uses: Nano-IT/workflows/.github/workflows/check.yml@v1

  build:
    needs: check
    uses: Nano-IT/workflows/.github/workflows/build-static.yml@v1

  deploy:
    needs: build
    uses: Nano-IT/workflows/.github/workflows/build.yml@v1
    secrets: inherit
    with:
      file: "codedeploy/Dockerfile"

  update-services:
    needs: deploy
    uses: Nano-IT/workflows/.github/workflows/update-services.yml@v1
    secrets: inherit
