name: Deploy PROD

on:
  push:
    tags:
      - '*'

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  release:
    needs: lint
    uses: ./.github/workflows/deploy-prod.yml
    secrets: inherit

