name: Tags

on:
  create:
    tags:
      - '*'

jobs:
  check:
    uses: Nano-IT/workflows/.github/workflows/check.yml

  build:
    needs: check
    uses: Nano-IT/workflows/.github/workflows/build.yml

  deploy:
    needs: build
    uses: Nano-IT/workflows/.github/workflows/deploy-prod.yml
    secrets: inherit

